development:
  bucket: dsafricashop
  access_key_id: 'AKIAIPJAWCTFHCNTM5AA'
  secret_access_key: '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'
production:
  bucket: dsafricashop
  access_key_id: 'AKIAIPJAWCTFHCNTM5AA'
  secret_access_key: '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'


  