#development:
#  bucket: ENV['S3_BUCKET'] #dsafricashop
#  access_key_id: ENV['S3_ACCESS_KEY'] #'AKIAIPJAWCTFHCNTM5AA'
#  secret_access_key:  ENV['S3_SECRET_KEY'] #'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'
production:
  bucket: ENV['S3_BUCKET']
  access_key_id: ENV['S3_ACCESS_KEY']
  secret_access_key: ENV['S3_SECRET_KEY']

